// Diner Dash
// #ID = 18133

// $964D7C: [Diner Location]
//          00=Diner
//          01=Mexican
//          02=Seafood
//          03=Retro
//          04=Goddess
//          05=Sushi
function diner_location() => byte(0x964D7C)

// $967B7E: Mode
//          0x00 - Career
//          0x01 - Endless Shift
function mode() => byte(0x967B7E)

// $967B80: [Choose Difficulty In Endless Shift]
//          00=Easy
//          01=Medium
//          02=Hard
function choose_difficulty_in_endless_shift() => byte(0x967B80)

// $99CD92: Diner Level 1 Star
function diner_level_1_star() => byte(0x99CD92)

// $99CDA7: Diner Level 2 Star
function diner_level_2_star() => byte(0x99CDA7)

// $99CDBB: Diner Level 3 Star
function diner_level_3_star() => byte(0x99CDBB)

// $99CDCF: Diner Level 4 Star
function diner_level_4_star() => byte(0x99CDCF)

// $99CDE3: Diner Level 5 Star
function diner_level_5_star() => byte(0x99CDE3)

// $99CDF7: Diner Level 6 Star
function diner_level_6_star() => byte(0x99CDF7)

// $99CE0B: Diner Level 7 Star
function diner_level_7_star() => byte(0x99CE0B)

// $99CE1F: Diner Level 8 Star
function diner_level_8_star() => byte(0x99CE1F)

// $99CE33: Diner Level 9 Star
function diner_level_9_star() => byte(0x99CE33)

// $99CE47: Diner Level 10 Star
function diner_level_10_star() => byte(0x99CE47)

// $99CE5B: Mexican Level 1 Star
function mexican_level_1_star() => byte(0x99CE5B)

// $99CE6F: Mexican Level 2 Star
function mexican_level_2_star() => byte(0x99CE6F)

// $99CE83: Mexican Level 3 Star
function mexican_level_3_star() => byte(0x99CE83)

// $99CE97: Mexican Level 4 Star
function mexican_level_4_star() => byte(0x99CE97)

// $99CEAB: Mexican Level 5 Star
function mexican_level_5_star() => byte(0x99CEAB)

// $99CEBF: Mexican Level 6 Star
function mexican_level_6_star() => byte(0x99CEBF)

// $99CED3: Mexican Level 7 Star
function mexican_level_7_star() => byte(0x99CED3)

// $99CEE7: Mexican Level 8 Star
function mexican_level_8_star() => byte(0x99CEE7)

// $99CEFB: Mexican Level 9 Star
function mexican_level_9_star() => byte(0x99CEFB)

// $99CF0F: Mexican Level 10 Star
function mexican_level_10_star() => byte(0x99CF0F)

// $99CF23: Seafood Level 1 Star
function seafood_level_1_star() => byte(0x99CF23)

// $99CF37: Seafood Level 2 Star
function seafood_level_2_star() => byte(0x99CF37)

// $99CF4B: Seafood Level 3 Star
function seafood_level_3_star() => byte(0x99CF4B)

// $99CF5F: Seafood Level 4 Star
function seafood_level_4_star() => byte(0x99CF5F)

// $99CF73: Seafood Level 5 Star
function seafood_level_5_star() => byte(0x99CF73)

// $99CF87: Seafood Level 6 Star
function seafood_level_6_star() => byte(0x99CF87)

// $99CF9B: Seafood Level 7 Star
function seafood_level_7_star() => byte(0x99CF9B)

// $99CFB0: Seafood Level 8 Star
function seafood_level_8_star() => byte(0x99CFAF)

// $99CFC3: Seafood Level 9 Star
function seafood_level_9_star() => byte(0x99CFC3)

// $99CFD7: Seafood Level 10 Star
function seafood_level_10_star() => byte(0x99CFD7)

// $99CFEB: Retro Level 1 Star
function retro_level_1_star() => byte(0x99CFEB)

// $99CFFF: Retro Level 2 Star
function retro_level_2_star() => byte(0x99CFFF)

// $99D013: Retro Level 3 Star
function retro_level_3_star() => byte(0x99D013)

// $99D027: Retro Level 4 Star
function retro_level_4_star() => byte(0x99D027)

// $99D03B: Retro Level 5 Star
function retro_level_5_star() => byte(0x99D03B)

// $99D04F: Retro Level 6 Star
function retro_level_6_star() => byte(0x99D04F)

// $99D063: Retro Level 7 Star
function retro_level_7_star() => byte(0x99D063)

// $99D077: Retro Level 8 Star
function retro_level_8_star() => byte(0x99D077)

// $99D08B: Retro Level 9 Star
function retro_level_9_star() => byte(0x99D08B)

// $99D09F: Retro Level 10 Star
function retro_level_10_star() => byte(0x99D09F)

// $99D0B3: Goddess Level 1 Star
function goddess_level_1_star() => byte(0x99D0B3)

// $99D0C7: Goddess Level 2 Star
function goddess_level_2_star() => byte(0x99D0C7)

// $99D0DB: Goddess Level 3 Star
function goddess_level_3_star() => byte(0x99D0DB)

// $99D0EF: Goddess Level 4 Star
function goddess_level_4_star() => byte(0x99D0EF)

// $99D103: Goddess Level 5 Star
function goddess_level_5_star() => byte(0x99D103)

// $99D117: Goddess Level 6 Star
function goddess_level_6_star() => byte(0x99D117)

// $99D12B: Goddess Level 7 Star
function goddess_level_7_star() => byte(0x99D12B)

// $99D13F: Goddess Level 8 Star
function goddess_level_8_star() => byte(0x99D13F)

// $99D153: Goddess Level 9 Star
function goddess_level_9_star() => byte(0x99D153)

// $99D167: Goddess Level 10 Star
function goddess_level_10_star() => byte(0x99D167)

// $99D17B: Sushi Level 1 Star
function sushi_level_1_star() => byte(0x99D17B)

// $99D18F: Sushi Level 2 Star
function sushi_level_2_star() => byte(0x99D18F)

// $99D1A0: Sushi Level 3 Star
function sushi_level_3_star() => byte(0x99D1A0)

// $99D1B7: Sushi Level 4 Star
function sushi_level_4_star() => byte(0x99D1B7)

// $99D1CB: Sushi Level 5 Star
function sushi_level_5_star() => byte(0x99D1CB)

// $99D1DF: Sushi Level 6 Star
function sushi_level_6_star() => byte(0x99D1DF)

// $99D1F3: Sushi Level 7 Star
function sushi_level_7_star() => byte(0x99D1F3)

// $99D207: Sushi Level 8 Star
function sushi_level_8_star() => byte(0x99D207)

// $99D21B: Sushi Level 9 Star
function sushi_level_9_star() => byte(0x99D21B)

// $99D22F: Sushi Level 10 Star
function sushi_level_10_star() => byte(0x99D22F)

// $99D243: Sushi Level 11 Star
function sushi_level_11_star() => byte(0x99D243)

// $99D257: Sushi Level 12 Star
function sushi_level_12_star() => byte(0x99D257)

// $99D26B: Sushi Level 13 Star
function sushi_level_13_star() => byte(0x99D26B)

// $99D27F: Sushi Level 14 Star
function sushi_level_14_star() => byte(0x99D27F)

// $99D293: Sushi Level 15 Star
function sushi_level_15_star() => byte(0x99D293)

// $99D2A7: Sushi Level 16 Star
function sushi_level_16_star() => byte(0x99D2A7)

// $99D2BB: Sushi Level 17 Star
function sushi_level_17_star() => byte(0x99D2BB)

// $99D2CF: Sushi Level 18 Star
function sushi_level_18_star() => byte(0x99D2CF)

// $99D2E3: Sushi Level 19 Star
function sushi_level_19_star() => byte(0x99D2E3)

// $99D2F7: Sushi Level 20 Star
function sushi_level_20_star() => byte(0x99D2F7)

// $9AF516: Paused=1
function paused() => byte(0x9AF516)

// $9AF518: Endless Shift Diner ID
function endless_shift_diner_id() => byte(0x9AF518)

// $9AF51C: [Level]
//          -1 Offset
//          00-09
//          0a=When Level 10 is finished and thrown back into Location Selector
function level() => byte(0x9AF51C)

// $9B0061: Endless Shift Stars
//          Easy=5
//          Medium=4
//          Hard=3
function endless_shift_stars() => byte(0x9B0061)

// $9B04D8: [Score] 32-bit
function score_32_bit() => dword(0x9B04D8)

// $A09C54: c8=Choose Difficulty Screen for Endless Difficulty
//          8c=Achievements
function c8_choose_difficulty_screen_for_endless_difficulty() => byte(0xA09C54)

// $B169E8: [Screen-Related]
//          00=In Game
//          01=Review Screen (Level Complete)/Advice Screen
//          02=Furniture Selection/Continue Screen
//          03=Diner Selector
//          04=Diner Selector Endless
//          
//          *Cycle: 0>1>2>1>2>0>1... (3 after second 2 if going back to Diner Selector)
function screen_related() => byte(0xB169E8)

// $EB57F8: [Select Mode]
//          fe=Load Game till Title Screen
//          00=Manage Profile(After Title Screen)
//          03=Career
//          04=Endless Shift
//          05=Multiplayer
//          06=High Scores
//          07=Options
//          08=Manage Profile(Through Select Mode)
function select_mode() => byte(0xEB57F8)

function game_mode() => byte(0x967b7e)

function career_mode()  { return game_mode() == 0}
function endless_mode() { return game_mode() == 1}

achievement(
    title = "Diner Day 1 Cleared!", points = 1, type="progression",
    description = "Clear Level 1",
    id = 185081, badge = "205792", 
    trigger = career_mode() && diner_location() == 0 && level() == 0 &&
              score_32_bit() >= 500 && screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Diner Day 2 Cleared!", points = 2, type="progression",
    description = "Clear Level 2",
    id = 185080, badge = "205791", 
    trigger = career_mode() && diner_location() == 0 && level() == 1 && score_32_bit() >= 1500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Diner Day 3 Cleared!", points = 3, type="progression",
    description = "Clear Level 3",
    id = 185082, badge = "205793", 
    trigger = career_mode() && diner_location() == 0 && level() == 2 && score_32_bit() >= 2200 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Diner Day 4 Cleared!", points = 4, type="progression",
    description = "Clear Level 4",
    id = 185083, badge = "205794",
    trigger = career_mode() && diner_location() == 0 && level() == 3 && score_32_bit() >= 3000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Diner Day 5 Cleared!", points = 5, type="progression",
    description = "Clear Level 5",
    id = 185084, badge = "205795", 
    trigger = career_mode() && diner_location() == 0 && level() == 4 && score_32_bit() >= 4300 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Diner Day 6 Cleared!", points = 5, type="progression",
    description = "Clear Level 6",
    id = 185085, badge = "205796", 
    trigger = career_mode() && diner_location() == 0 && level() == 5 && score_32_bit() >= 5000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Diner Day 7 Cleared!", points = 5, type="progression",
    description = "Clear Level 7",
    id = 185086, badge = "205797", 
    trigger = career_mode() && diner_location() == 0 && level() == 6 && score_32_bit() >= 5500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Diner Day 8 Cleared!", points = 5, type="progression",
    description = "Clear Level 8",
    id = 185087, badge = "205798",
    trigger = career_mode() && diner_location() == 0 && level() == 7 && score_32_bit() >= 5800 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Diner Day 9 Cleared!", points = 5, type="progression",
    description = "Clear Level 9",
    id = 185089, badge = "205800", 
    trigger = career_mode() && diner_location() == 0 && level() == 8 && score_32_bit() >= 6800 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Diner Day 10 Cleared!", points = 5, type="progression",
    description = "Clear Level 10",
    id = 185088, badge = "205799", 
    trigger = career_mode() && diner_location() == 0 && level() == 9 && score_32_bit() >= 7500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Diner Expert Chef", points = 10,
    description = "Get Expert on Level 10 in Diner",
    id = 185156, badge = "205867", 
    trigger = career_mode() && diner_location() == 0 && level() == 9 && score_32_bit() >= 10000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Mexican Day 1 Cleared!", points = 3, type="progression",
    description = "Clear Level 1",
    id = 185090, badge = "205801",
    trigger = career_mode() && diner_location() == 1 && level() == 0 && score_32_bit() >= 2200 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Mexican Day 2 Cleared!", points = 3, type="progression",
    description = "Clear Level 2",
    id = 185091, badge = "205802", 
    trigger = career_mode() && diner_location() == 1 && level() == 1 && score_32_bit() >= 3000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Mexican Day 3 Cleared!", points = 4, type="progression",
    description = "Clear Level 3",
    id = 185092, badge = "205803", 
    trigger = career_mode() && diner_location() == 1 && level() == 2 && score_32_bit() >= 3700 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Mexican Day 4 Cleared!", points = 4, type="progression",
    description = "Clear Level 4",
    id = 185093, badge = "205804", 
    trigger = career_mode() && diner_location() == 1 && level() == 3 && score_32_bit() >= 4500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Mexican Day 5 Cleared!", points = 5, type="progression",
    description = "Clear Level 5",
    id = 185094, badge = "205805", 
    trigger = career_mode() && diner_location() == 1 && level() == 4 && score_32_bit() >= 5000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Mexican Day 6 Cleared!", points = 5, type="progression",
    description = "Clear Level 6",
    id = 185095, badge = "205806", 
    trigger = career_mode() && diner_location() == 1 && level() == 5 && score_32_bit() >= 5500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Mexican Day 7 Cleared!", points = 5, type="progression",
    description = "Clear Level 7",
    id = 185096, badge = "205807", 
    trigger = career_mode() && diner_location() == 1 && level() == 6 && score_32_bit() >= 6000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Mexican Day 8 Cleared!", points = 5, type="progression",
    description = "Clear Level 8",
    id = 185097, badge = "205808", 
    trigger = career_mode() && diner_location() == 1 && level() == 7 && score_32_bit() >= 6500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Mexican Day 9 Cleared!", points = 5, type="progression",
    description = "Clear Level 9",
    id = 185098, badge = "205809", 
    trigger = career_mode() && diner_location() == 1 && level() == 8 && score_32_bit() >= 7200 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Mexican Day 10 Cleared!", points = 10, type="progression",
    description = "Clear Level 10",
    id = 185099, badge = "205810", 
    trigger = career_mode() && diner_location() == 1 && level() == 9 && score_32_bit() >= 7500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Mexican Expert Chef", points = 10,
    description = "Get Expert on Level 10 in Mexican",
    id = 185157, badge = "205868", 
    trigger = career_mode() && diner_location() == 1 && level() == 9 && score_32_bit() >= 10000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Seafood Day 1 Cleared!", points = 3, type="progression",
    description = "Clear Level 1",
    id = 185100, badge = "205811", 
    trigger = career_mode() && diner_location() == 2 && level() == 0 && score_32_bit() >= 3000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Seafood Day 2 Cleared!", points = 3, type="progression",
    description = "Clear Level 2",
    id = 185101, badge = "205812", 
    trigger = career_mode() && diner_location() == 2 && level() == 1 && score_32_bit() >= 3500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Seafood Day 3 Cleared!", points = 4, type="progression",
    description = "Clear Level 3",
    id = 185102, badge = "205813", 
    trigger = career_mode() && diner_location() == 2 && level() == 2 && score_32_bit() >= 4000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Seafood Day 4 Cleared!", points = 4, type="progression",
    description = "Clear Level 4",
    id = 185103, badge = "205814", 
    trigger = career_mode() && diner_location() == 2 && level() == 3 && score_32_bit() >= 4600 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Seafood Day 5 Cleared!", points = 5, type="progression",
    description = "Clear Level 5",
    id = 185104, badge = "205815", 
    trigger = career_mode() && diner_location() == 2 && level() == 4 && score_32_bit() >= 5200 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Seafood Day 6 Cleared!", points = 5, type="progression",
    description = "Clear Level 6",
    id = 185105, badge = "205816", 
    trigger = career_mode() && diner_location() == 2 && level() == 5 && score_32_bit() >= 5800 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Seafood Day 7 Cleared!", points = 5, type="progression",
    description = "Clear Level 7",
    id = 185106, badge = "205817", 
    trigger = career_mode() && diner_location() == 2 && level() == 6 && score_32_bit() >= 6300 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Seafood Day 8 Cleared!", points = 5, type="progression",
    description = "Clear Level 8",
    id = 185107, badge = "205818", 
    trigger = career_mode() && diner_location() == 2 && level() == 7 && score_32_bit() >= 6800 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Seafood Day 9 Cleared!", points = 5, type="progression",
    description = "Clear Level 9",
    id = 185108, badge = "205819",
    trigger = career_mode() && diner_location() == 2 && level() == 8 && score_32_bit() >= 7500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Seafood Day 10 Cleared!", points = 10, type="progression",
    description = "Clear Level 10",
    id = 185109, badge = "205820", 
    trigger = career_mode() && diner_location() == 2 && level() == 9 && score_32_bit() >= 8000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Seafood Expert Chef", points = 10,
    description = "Get Expert on Level 10 in Seafood",
    id = 185158, badge = "205869", 
    trigger = career_mode() && diner_location() == 2 && level() == 9 && score_32_bit() >= 12000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Retro Day 1 Cleared!", points = 3, type="progression",
    description = "Clear Level 1",
    id = 185110, badge = "205821", 
    trigger = career_mode() && diner_location() == 3 && level() == 0 && score_32_bit() >= 3000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Retro Day 2 Cleared!", points = 3, type="progression",
    description = "Clear Level 2",
    id = 185111, badge = "205822",
    trigger = career_mode() && diner_location() == 3 && level() == 1 && score_32_bit() >= 3500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Retro Day 3 Cleared!", points = 4, type="progression",
    description = "Clear Level 3",
    id = 185112, badge = "205823",
    trigger = career_mode() && diner_location() == 3 && level() == 2 && score_32_bit() >= 4000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Retro Day 4 Cleared!", points = 4, type="progression",
    description = "Clear Level 4",
    id = 185113, badge = "205824", 
    trigger = career_mode() && diner_location() == 3 && level() == 3 && score_32_bit() >= 4500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Retro Day 5 Cleared!", points = 5, type="progression",
    description = "Clear Level 5",
    id = 185114, badge = "205825", 
    trigger = career_mode() && diner_location() == 3 && level() == 4 && score_32_bit() >= 5000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Retro Day 6 Cleared!", points = 5, type="progression",
    description = "Clear Level 6",
    id = 185115, badge = "205826", 
    trigger = career_mode() && diner_location() == 3 && level() == 5 && score_32_bit() >= 5500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Retro Day 7 Cleared!", points = 5, type="progression",
    description = "Clear Level 7",
    id = 185116, badge = "205827", 
    trigger = career_mode() && diner_location() == 3 && level() == 6 && score_32_bit() >= 6200 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Retro Day 8 Cleared!", points = 5, type="progression",
    description = "Clear Level 8",
    id = 185117, badge = "205828", 
    trigger = career_mode() && diner_location() == 3 && level() == 7 && score_32_bit() >= 7000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Retro Day 9 Cleared!", points = 5, type="progression",
    description = "Clear Level 9",
    id = 185118, badge = "205829", 
    trigger = career_mode() && diner_location() == 3 && level() == 8 && score_32_bit() >= 7600 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Retro Day 10 Cleared!", points = 10, type="progression",
    description = "Clear Level 10",
    id = 185119, badge = "205830", 
    trigger = career_mode() && diner_location() == 3 && level() == 9 && score_32_bit() >= 8200 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Retro Expert Chef", points = 10,
    description = "Get Expert on Level 10 in Retro",
    id = 185159, badge = "205870", 
    trigger = career_mode() && diner_location() == 3 && level() == 9 && score_32_bit() >= 11000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Goddess Day 1 Cleared!", points = 3, type="progression",
    description = "Clear Level 1",
    id = 185120, badge = "205831", 
    trigger = career_mode() && diner_location() == 4 && level() == 0 && score_32_bit() >= 3000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Goddess Day 2 Cleared!", points = 3, type="progression",
    description = "Clear Level 2",
    id = 185122, badge = "205833", 
    trigger = career_mode() && diner_location() == 4 && level() == 1 && score_32_bit() >= 3800 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Goddess Day 3 Cleared!", points = 4, type="progression",
    description = "Clear Level 3",
    id = 185123, badge = "205834", 
    trigger = career_mode() && diner_location() == 4 && level() == 2 && score_32_bit() >= 4400 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Goddess Day 4 Cleared!", points = 4, type="progression",
    description = "Clear Level 4",
    id = 185124, badge = "205835",
    trigger = career_mode() && diner_location() == 4 && level() == 3 && score_32_bit() >= 5200 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Goddess Day 5 Cleared!", points = 5, type="progression",
    description = "Clear Level 5",
    id = 185125, badge = "205836", 
    trigger = career_mode() && diner_location() == 4 && level() == 4 && score_32_bit() >= 6000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Goddess Day 6 Cleared!", points = 5, type="progression",
    description = "Clear Level 6",
    id = 185126, badge = "205837",
    trigger = career_mode() && diner_location() == 4 && level() == 5 && score_32_bit() >= 6500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Goddess Day 7 Cleared!", points = 5, type="progression",
    description = "Clear Level 7",
    id = 185127, badge = "205838",
    trigger = career_mode() && diner_location() == 4 && level() == 6 && score_32_bit() >= 7000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Goddess Day 8 Cleared!", points = 5, type="progression",
    description = "Clear Level 8",
    id = 185128, badge = "205839", 
    trigger = career_mode() && diner_location() == 4 && level() == 7 && score_32_bit() >= 7800 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Goddess Day 9 Cleared!", points = 5, type="progression",
    description = "Clear Level 9",
    id = 185129, badge = "205840",
    trigger = career_mode() && diner_location() == 4 && level() == 8 && score_32_bit() >= 8500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Goddess Day 10 Cleared!", points = 10, type="progression",
    description = "Clear Level 10",
    id = 185121, badge = "205832",
    trigger = career_mode() && diner_location() == 4 && level() == 9 && score_32_bit() >= 9500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Goddess Expert Chef", points = 10,
    description = "Get Expert on Level 10 in Goddess",
    id = 185079, badge = "205790",
    trigger = career_mode() && diner_location() == 4 && level() == 9 && score_32_bit() >= 13500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 1 Cleared!", points = 5, type="progression",
    description = "Clear Level 1",
    id = 185130, badge = "205841", 
    trigger = career_mode() && diner_location() == 5 && level() == 0 && score_32_bit() >= 3500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 2 Cleared!", points = 5, type="progression",
    description = "Clear Level 2",
    id = 185132, badge = "205843", 
    trigger = career_mode() && diner_location() == 5 && level() == 1 && score_32_bit() >= 5000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 3 Cleared!", points = 5, type="progression",
    description = "Clear Level 3",
    id = 185133, badge = "205844", 
    trigger = career_mode() && diner_location() == 5 && level() == 2 && score_32_bit() >= 6500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 4 Cleared!", points = 5, type="progression",
    description = "Clear Level 4",
    id = 185134, badge = "205845",
    trigger = career_mode() && diner_location() == 5 && level() == 3 && score_32_bit() >= 7500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 5 Cleared!", points = 5, type="progression",
    description = "Clear Level 5",
    id = 185135, badge = "205846", 
    trigger = career_mode() && diner_location() == 5 && level() == 4 && score_32_bit() >= 4500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 6 Cleared!", points = 5, type="progression",
    description = "Clear Level 6",
    id = 185136, badge = "205847", 
    trigger = career_mode() && diner_location() == 5 && level() == 5 && score_32_bit() >= 5200 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 7 Cleared!", points = 5, type="progression",
    description = "Clear Level 7",
    id = 185137, badge = "205848", 
    trigger = career_mode() && diner_location() == 5 && level() == 6 && score_32_bit() >= 6000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 8 Cleared!", points = 5, type="progression",
    description = "Clear Level 8",
    id = 185138, badge = "205849", 
    trigger = career_mode() && diner_location() == 5 && level() == 7 && score_32_bit() >= 7000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 9 Cleared!", points = 5, type="progression",
    description = "Clear Level 9",
    id = 185139, badge = "205850", 
    trigger = career_mode() && diner_location() == 5 && level() == 8 && score_32_bit() >= 3500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 10 Cleared!", points = 5, type="progression",
    description = "Clear Level 10",
    id = 185131, badge = "205842", 
    trigger = career_mode() && diner_location() == 5 && level() == 9 && score_32_bit() >= 4000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 11 Cleared!", points = 10, type="progression",
    description = "Clear Level 11",
    id = 185140, badge = "205851", 
    trigger = career_mode() && diner_location() == 5 && level() == 10 && score_32_bit() >= 4500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 12 Cleared!", points = 10, type="progression",
    description = "Clear Level 12",
    id = 185141, badge = "205852", 
    trigger = career_mode() && diner_location() == 5 && level() == 11 && score_32_bit() >= 5000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 13 Cleared!", points = 10, type="progression",
    description = "Clear Level 13",
    id = 185142, badge = "205853", 
    trigger = career_mode() && diner_location() == 5 && level() == 12 && score_32_bit() >= 4000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 14 Cleared!", points = 10, type="progression",
    description = "Clear Level 14",
    id = 185143, badge = "205854", 
    trigger = career_mode() && diner_location() == 5 && level() == 13 && score_32_bit() >= 4500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 15 Cleared!", points = 10, type="progression",
    description = "Clear Level 15",
    id = 185144, badge = "205855", 
    trigger = career_mode() && diner_location() == 5 && level() == 14 && score_32_bit() >= 5000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 16 Cleared!", points = 10, type="progression",
    description = "Clear Level 16",
    id = 185145, badge = "205856", 
    trigger = career_mode() && diner_location() == 5 && level() == 15 && score_32_bit() >= 5500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 17 Cleared!", points = 10, type="progression",
    description = "Clear Level 17",
    id = 185146, badge = "205857", 
    trigger = career_mode() && diner_location() == 5 && level() == 16 && score_32_bit() >= 4000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 18 Cleared!", points = 10, type="progression",
    description = "Clear Level 18",
    id = 185147, badge = "205858", 
    trigger = career_mode() && diner_location() == 5 && level() == 17 && score_32_bit() >= 4500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 19 Cleared!", points = 10, type="progression",
    description = "Clear Level 19",
    id = 185148, badge = "205859", 
    trigger = career_mode() && diner_location() == 5 && level() == 18 && score_32_bit() >= 5000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Day 20 Cleared!", points = 10, type="progression",
    description = "Clear Level 20",
    id = 185149, badge = "205860", 
    trigger = career_mode() && diner_location() == 5 && level() == 19 && score_32_bit() >= 6500 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Sushi Expert Chef", points = 10,
    description = "Get Expert on Level 8 in Sushi",
    id = 185078, badge = "205789", 
    trigger = career_mode() && diner_location() == 5 && level() == 7 && score_32_bit() >= 11000 &&
              screen_related() == 1 && disable_when(paused() == 1, until=paused() == 0)
)

achievement(
    title = "Diner Master Chef", points = 10,
    description = "Reach a score of at least 100,000 on Endless Shift (Any Mode)",
    id = 185150, badge = "205872", 
    trigger = endless_mode() && endless_shift_diner_id() == 0 && score_32_bit() >= 100000 &&
              score_32_bit() > prev(score_32_bit()) &&
              once(endless_shift_stars() >= 3 && never(endless_shift_stars() == 0))
)

achievement(
    title = "Mexican Master Chef", points = 10,
    description = "Reach a score of at least 100,000 on Endless Shift (Any Mode)",
    id = 185151, badge = "205871", 
    trigger = endless_mode() && endless_shift_diner_id() == 1 && score_32_bit() >= 100000 &&
              score_32_bit() > prev(score_32_bit()) &&
              once(endless_shift_stars() >= 3 && never(endless_shift_stars() == 0))
)

achievement(
    title = "Seafood Master Chef", points = 10,
    description = "Reach a score of at least 100,000 on Endless Shift (Any Mode)",
    id = 185152, badge = "205863", 
    trigger = endless_mode() && endless_shift_diner_id() == 2 && score_32_bit() >= 100000 &&
              score_32_bit() > prev(score_32_bit()) &&
              once(endless_shift_stars() >= 3 && never(endless_shift_stars() == 0))
)

achievement(
    title = "Retro Master Chef", points = 10,
    description = "Reach a score of at least 100,000 on Endless Shift (Any Mode)",
    id = 185153, badge = "205864", 
    trigger = endless_mode() && endless_shift_diner_id() == 3 && score_32_bit() >= 100000 &&
              score_32_bit() > prev(score_32_bit()) &&
              once(endless_shift_stars() >= 3 && never(endless_shift_stars() == 0))
)

achievement(
    title = "Goddess Master Chef", points = 25,
    description = "Reach a score of at least 150,000 on Endless Shift (Any Mode)",
    id = 185154, badge = "205865", 
    trigger = endless_mode() && endless_shift_diner_id() == 4 && score_32_bit() >= 150000 &&
              score_32_bit() > prev(score_32_bit()) &&
              once(endless_shift_stars() >= 3 && never(endless_shift_stars() == 0))
)

achievement(
    title = "Sushi Master Chef", points = 25,
    description = "Reach a score of at least 100,000 on Endless Shift (Any Mode)",
    id = 185155, badge = "205866",
    trigger = endless_mode() && endless_shift_diner_id() == 5 && score_32_bit() >= 100000 &&
              score_32_bit() > prev(score_32_bit()) &&
              once(endless_shift_stars() >= 3 && never(endless_shift_stars() == 0))
)

achievement(
    title = "Gordon Would Be Very Proud", points = 50,
    description = "Thank you for providing excellent food service. (Expert all levels)",
    id = 185077, badge = "205788", 
    trigger = (prev(diner_level_1_star()) + prev(diner_level_2_star()) + prev(diner_level_3_star()) +
              prev(diner_level_4_star()) + prev(diner_level_5_star()) + prev(diner_level_6_star()) +
              prev(diner_level_7_star()) + prev(diner_level_8_star()) + prev(diner_level_9_star()) +
              prev(diner_level_10_star()) + prev(mexican_level_1_star()) + prev(mexican_level_2_star()) +
              prev(mexican_level_3_star()) + prev(mexican_level_4_star()) + prev(mexican_level_5_star()) +
              prev(mexican_level_6_star()) + prev(mexican_level_7_star()) + prev(mexican_level_8_star()) +
              prev(mexican_level_9_star()) + prev(mexican_level_10_star()) + prev(seafood_level_1_star()) +
              prev(seafood_level_2_star()) + prev(seafood_level_3_star()) + prev(seafood_level_4_star()) +
              prev(seafood_level_5_star()) + prev(seafood_level_6_star()) + prev(seafood_level_7_star()) +
              prev(seafood_level_8_star()) + prev(seafood_level_9_star()) + prev(seafood_level_10_star()) +
              prev(retro_level_1_star()) + prev(retro_level_2_star()) + prev(retro_level_3_star()) +
              prev(retro_level_4_star()) + prev(retro_level_5_star()) + prev(retro_level_6_star()) +
              prev(retro_level_7_star()) + prev(retro_level_8_star()) + prev(retro_level_9_star()) +
              prev(retro_level_10_star()) + prev(goddess_level_1_star()) + prev(goddess_level_2_star()) +
              prev(goddess_level_3_star()) + prev(goddess_level_4_star()) + prev(goddess_level_5_star()) +
              prev(goddess_level_6_star()) + prev(goddess_level_7_star()) + prev(goddess_level_8_star()) +
              prev(goddess_level_9_star()) + prev(goddess_level_10_star()) + prev(sushi_level_1_star()) +
              prev(sushi_level_2_star()) + prev(sushi_level_3_star()) + prev(sushi_level_4_star()) +
              prev(sushi_level_5_star()) + prev(sushi_level_6_star()) + prev(sushi_level_7_star()) +
              prev(sushi_level_8_star()) + prev(sushi_level_9_star()) + prev(sushi_level_10_star()) +
              prev(sushi_level_11_star()) + prev(sushi_level_12_star()) + prev(sushi_level_13_star()) +
              prev(sushi_level_14_star()) + prev(sushi_level_15_star()) + prev(sushi_level_16_star()) +
              prev(sushi_level_17_star()) + prev(sushi_level_18_star()) + prev(sushi_level_19_star()) +
              prev(sushi_level_20_star())) == 68 &&
              measured((diner_level_1_star() + diner_level_2_star() + diner_level_3_star() + diner_level_4_star() +
                  diner_level_5_star() + diner_level_6_star() + diner_level_7_star() + diner_level_8_star() +
                  diner_level_9_star() + diner_level_10_star() + mexican_level_1_star() + mexican_level_2_star() +
                  mexican_level_3_star() + mexican_level_4_star() + mexican_level_5_star() + mexican_level_6_star() +
                  mexican_level_7_star() + mexican_level_8_star() + mexican_level_9_star() + mexican_level_10_star() +
                  seafood_level_1_star() + seafood_level_2_star() + seafood_level_3_star() + seafood_level_4_star() +
                  seafood_level_5_star() + seafood_level_6_star() + seafood_level_7_star() + seafood_level_8_star() +
                  seafood_level_9_star() + seafood_level_10_star() + retro_level_1_star() + retro_level_2_star() +
                  retro_level_3_star() + retro_level_4_star() + retro_level_5_star() + retro_level_6_star() +
                  retro_level_7_star() + retro_level_8_star() + retro_level_9_star() + retro_level_10_star() +
                  goddess_level_1_star() + goddess_level_2_star() + goddess_level_3_star() + goddess_level_4_star() +
                  goddess_level_5_star() + goddess_level_6_star() + goddess_level_7_star() + goddess_level_8_star() +
                  goddess_level_9_star() + goddess_level_10_star() + sushi_level_1_star() + sushi_level_2_star() +
                  sushi_level_3_star() + sushi_level_4_star() + sushi_level_5_star() + sushi_level_6_star() +
                  sushi_level_7_star() + sushi_level_8_star() + sushi_level_9_star() + sushi_level_10_star() +
                  sushi_level_11_star() + sushi_level_12_star() + sushi_level_13_star() + sushi_level_14_star() +
                  sushi_level_15_star() + sushi_level_16_star() + sushi_level_17_star() + sushi_level_18_star() +
                  sushi_level_19_star() + sushi_level_20_star()) == 69
              )
)

leaderboard(
    id = 28002, title = "Endless Shift: Diner",
    description = "on Easy",
    start  = endless_shift_diner_id() == 0 && choose_difficulty_in_endless_shift() == 0 && endless_shift_stars() == 5,
    cancel = c8_choose_difficulty_screen_for_endless_difficulty() == 140,
    submit = endless_shift_stars() == 0,
    value  = score_32_bit(),
    format = "VALUE"
)

leaderboard(
    id = 28007, title = "Endless Shift: Mexican",
    description = "on Easy",
    start  = endless_shift_diner_id() == 1 && choose_difficulty_in_endless_shift() == 0 && endless_shift_stars() == 5,
    cancel = c8_choose_difficulty_screen_for_endless_difficulty() == 140,
    submit = endless_shift_stars() == 0,
    value  = score_32_bit(),
    format = "VALUE"
)

leaderboard(
    id = 28008, title = "Endless Shift: Seafood",
    description = "on Easy",
    start  = endless_shift_diner_id() == 2 && choose_difficulty_in_endless_shift() == 0 && endless_shift_stars() == 5,
    cancel = c8_choose_difficulty_screen_for_endless_difficulty() == 140,
    submit = endless_shift_stars() == 0,
    value  = score_32_bit(),
    format = "VALUE"
)

leaderboard(
    id = 28009, title = "Endless Shift: Retro",
    description = "on Easy",
    start  = endless_shift_diner_id() == 3 && choose_difficulty_in_endless_shift() == 0 && endless_shift_stars() == 5,
    cancel = c8_choose_difficulty_screen_for_endless_difficulty() == 140,
    submit = endless_shift_stars() == 0,
    value  = score_32_bit(),
    format = "VALUE"
)

leaderboard(
    id = 28010, title = "Endless Shift: Goddess",
    description = "on Easy",
    start  = endless_shift_diner_id() == 4 && choose_difficulty_in_endless_shift() == 0 && endless_shift_stars() == 5,
    cancel = c8_choose_difficulty_screen_for_endless_difficulty() == 140,
    submit = endless_shift_stars() == 0,
    value  = score_32_bit(),
    format = "VALUE"
)

leaderboard(
    id = 28011, title = "Endless Shift: Sushi",
    description = "on Easy",
    start  = endless_shift_diner_id() == 5 && choose_difficulty_in_endless_shift() == 0 && endless_shift_stars() == 5,
    cancel = c8_choose_difficulty_screen_for_endless_difficulty() == 140,
    submit = endless_shift_stars() == 0,
    value  = score_32_bit(),
    format = "VALUE"
)
